### ISSUE TITLE
Using LD from reference panel

### ISSUE THREAD

**Issue by zx8754** [stephenslab/susieR#104]
Struggling to understand the formula given to calculate **R_ref** in the manuals:

![image](https://user-images.githubusercontent.com/5212915/78653250-c7d38600-78ba-11ea-9d3f-36c666a514f0.png)

Could you clarify based on below settings I have:
- z_scores for 1000 SNPs (from 100000 sample data)
- reference panel: 20000 samples, 1000 same SNPs.

Questions:
 - **w** weight would be: 1/20000 ?
 - **X ref** is the panel genotype matrix with rows 20000 samples and columns 1000 SNPs?
 - Why transpose and multiply **X^T ref** ?
 - What is **z^T**, how transposing a vector help?
 - Do we need to set **z_ld_weight = 1/100000**, too?
 
Apologies, probably missing basic understanding of how this package is supposed to work, appreciate any input. Thank you.

**Comment by zouyuxin** [comment]
> w weight would be: 1/20000 ?

Yes
> X ref is the panel genotype matrix with rows 20000 samples and columns 1000 SNPs?

Yes, and it should be column standardized (column mean 0, variance 1)
> Why transpose and multiply X^T ref ?

This is how we compute sample correlation, X_ref^T X_ref / n_ref
> What is z^T, how transposing a vector help?

z^T is the transpose of your z score vector. In the formula, we use z z^T, which is a matrix (1000 x 1000 matrix).
> Do we need to set z_ld_weight = 1/100000, too?

No, z_ld_weight = 1/20000.

Your susie call should like
`susie_rss(z=z, R=cor(X_ref), L=10, z_ld_weight=1/20000, estimate_residual_variance=T, estimate_prior_variance=T)`
cor(X_ref) is the LD matrix, it is X_ref^T X_ref / (n_ref-1) with column-standardized X_ref

**Comment by zx8754** [comment]
@zouyuxin Thank you, this should get me going.
