### ISSUE TITLE
Reporting per-snp BFs

### ISSUE THREAD

**Issue by trb8** [stephenslab/susieR#109]
Hi
Thanks for the great method/package. Will it be possible to report the per-SNP BFs (for each single effect) using e.g.
s$snplbf[l,] <- res$lbf in update_each_effect_ss

Those BF will be useful for coloc analyses as in COLOC [here](https://journals.plos.org/plosgenetics/article/file?id=10.1371/journal.pgen.1004383.s015&type=supplementary) . The COLOC method itself assumes a single effect so there is a need.

Thanks,
Tushar

**Comment by stephens999** [comment]
I agree this would be useful, and is certainly something we have used
ourselves in the past.
If it is not yet an option we should add it.

**Comment by trb8** [comment]
Great! Thank you.

**Comment by pcarbo** [comment]
Hi @trb8. I just want to make sure I understand your request. 

The idea would be to create an output, let's call it `lbf`, that is a p x L matrix, where p is the number of variables and L is the number of single effects, in which `lbf[i,j]` is the log-Bayes factor for variable i and single effect j. Is that what you looking for?

**Comment by gaow** [comment]
@pcarbo sorry I have added it earlier but not tests and documentations to it yet ... I'll handle this and other issues #111 this evening on my calendar.

**Comment by trb8** [comment]
@pcarbo yes, that's what I meant 
Thanks @gaow

**Comment by pcarbo** [comment]
@trb8 `susie` and `susie_rss` now include an output `lbf_variable`. It is a matrix containing the per-SNP Bayes factors. Please let us know if you have any questions about this, or anything else.

**Comment by pcarbo** [comment]
@trb8 I neglected to mention that this is implemented in the `cran` branch.
