### ISSUE TITLE
Finemapping multiple traits using susieR?

### ISSUE THREAD

**Issue by MalteThodberg** [stephenslab/susieR#110]
Can susieR do finemapping using multiple traits across a single loci? (similar to fastPAINTOR: https://pubmed.ncbi.nlm.nih.gov/27663501/)

**Comment by gaow** [comment]
@MalteThodberg we are working on this package & manuscript:

https://github.com/stephenslab/mmbr

Currently the package works, although we are still making some changes to it, before we can release a beta version.
