### ISSUE TITLE
Tasks for preparing CRAN submission

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/susieR#111]
@gaow I will use this issue to keep track of tasks for the CRAN submission. *Please commit all changes the `cran` branch.*

- [x] Add example for `compute_ss`.
- [x] Add example for `susie_init_coef`.
- [x] Add examples to `help(susie_get_methods)`.
- [x] Add examples to `help(susie_plots)`.
- [x] Write roxygen2 docs `univariate_regression`.
- [x] Fill out roxygen2 docs for `N2finemapping` data set.
- [x] Fill out roxygen2 docs for `N3finemapping` data set.

See [here](https://github.com/stephenslab/mixsqp/blob/master/R/tacks.R) for an example of a help page for a data set (this example is taken from the mixsqp package).

**Comment by gaow** [comment]
@pcarbo I've added examples and documentations as you listed above. Please reopen if additional contents need to be added.

**Comment by pcarbo** [comment]
Thanks @gaow!

**Comment by pcarbo** [comment]
@gaow I'm going to leave this open—as I go through your changes I see that there are a few more small things we need to take care of.

**Comment by pcarbo** [comment]
+ [ ] Add `susie_auto` example in `susie.R`.
+ [ ] Add `univariate_regression` example.
+ [ ] Fix `N3finemapping` docs; in particular the description in `@format` does not match the contents of `N3finemapping`.

**Comment by gaow** [comment]
issues @gaow would like to address to before release
+ [ ] #93 
+ [ ] #92 
+ [ ] #82 make a  section in a vignette, and not implement it
+ [ ] #69 
+ [ ] #52 
+ [ ] #44 

Will work with @zouyuxin on: 

+ [ ] #66 
+ [ ] #7 

if she's available.

**Comment by pcarbo** [comment]
@gaow This is all great. I will wait to hear back from you then before proceeding on the CRAN submission. 

At this stage, I think it would be best to implement all these improvements in the `cran` branch.

**Comment by gaow** [comment]
@pcarbo @stephens999  the only unchecked  box in [this list](https://github.com/stephenslab/susieR/issues/111#issuecomment-703684355) was #7 but I went ahead closed it anyways because I agree with @pcarbo 's fix. Otherwise we should submit to cran I think. @pcarbo shall we do it whenever you get a chance?
