### ISSUE TITLE
Mixture models/GLM 

### ISSUE THREAD

**Issue by mariellabogoni** [stephenslab/susieR#115]
is possible to extend to mixture models? or generalized linear models such as logistic model?
thank you!

**Comment by gaow** [comment]
@mariellabogoni what do you mean by mixture model -- would you elaborate?

**Comment by katherinef** [comment]
I would also be interested in this functionality, particularly logistic regression for binary outcomes.
I assume "mixture models" means linear mixed models like those implemented in BOLT-LMM that can account for genetic relatedness between individuals.

Thanks!

Kath

**Comment by stephens999** [comment]
the most general approach we have is `susie_rss` (susie regression with summary statistics) 
which applies susie to z scores and an LD matrix.
So, for example, you can 
compute z scores under a logistic regression, or mixed model, and apply `susie_rss` to those z scores. 
We have attempted to make susie_rss somewhat robust to misspecification of the LD matrix and continue to work on
further improving this.  You should be able to get more help with ?susie_rss

For the specific case of logistic regression we have also implemented a version of susie specific to the logistic model.
It is not really clear whether this is better than using susie_rss on z scores, or even just applying susie with a binary outcome
(if effect sizes are small, as they are in most genetic studies, logistic regression and linear regression usually produce very similar results).  But we have implemented it. @andrewg3311 is responsible for that work, and I'll let him point you
to anything he can share as it is very much "work in progress".
