### ISSUE TITLE
Definition of purity of CS

### ISSUE THREAD

**Issue by gaow** [stephenslab/susieR#117]
In SuSiE paper we defined purity as the minimum absolute correlation between variables in a CS. I cannot remember if it was a decision after discussions or it was my fault to do that; it feels like a natural choice (in fact we use correlation matrix as "LD" matrix in susie_rss). However this may cause a confusion when we report to people in genetics the community is used to seeing r^2 and thinking in terms of r^2. Our definition can cause a confusion.

Currently, the default [purity cutoff to filter CS is 0.5](https://github.com/stephenslab/susieR/blob/master/R/susie_utils.R#L249) which is r^2 0.25 and is reasonable. We do have a switch `squared` in `susie_get_cs` currently set to `False`. If we change the behavior to `True` by default and change the cutoff to 0.25 that wont impact any previous anlaysis. 

Perhaps maybe to keep it consistent with SuSiE paper definition we still call our current purity as is, and additionally also report r^2? What do we want to call that? Or, @stephens999 do you have other suggestions?

**Comment by stephens999** [comment]
on reflection i think we should stick to how we defined it in the paper. Changing may create additional confusion.
