### ISSUE TITLE
slow convergence example

### ISSUE THREAD

**Issue by stephens999** [stephenslab/susieR#123]
Here is [example 5](https://www.dropbox.com/s/oak2x5lqs6rofai/test_data5.rds?dl=0), which eventually converges with an in-sample LD matrix (generated by plink using 341k unrelated UK biobank samples).

_Originally posted by @joshchiou in https://github.com/stephenslab/susieR/issues/122#issuecomment-833220143_

**Comment by stephens999** [comment]
@joshchiou I'm going to follow up this example separately  when i get time....

**Comment by stephens999** [comment]
this is an interesting example.
First it is clear this region seems complex: susie find 9 CSs!
So I think it is not that surprising that convergence is slower than usual.

Some additional comments are probably in order:

i) many of the signals identified have small non-significant marginal z scores.
The reason they are identified in the multi-snp analysis is
because they are in high LD with another variant with strong z score, and yet *don't* themselves have a strong z score.
The only way a variant can be in high LD with a strongly-associated variant and yet not show a strong z score itself
is if there is another compensatory signal that cancels out the strong z score.
This is probably the hardest kind of example to finemap. (Of course an alternative
possibility is somehow the z scores or ld matrix are wrong, but I do not see any evidence for that.)

ii) To check for convergence issues i reran susie with "refine=TRUE". This takes several hours in this case
because there are so many signals. It did find a better solution, but with one additional signal compared with
those found in the original run. 

I don't think there is a problem per se with these results, but in complex regions like this the space is
likely to be quite complex and it is possible that susie could converge to a local optima, so although my best guess is that
the CSs identified here are mostly reliable, in complex situations like this -- 9+ signals, some cancelling each other out
in the marginal associations -- it is harder to be
confident in any given mapped signal.

Thanks for sharing this interesting example with us.
Please close this issue if you don't have additional questions or concerns.

**Comment by joshchiou** [comment]
Thank you for taking a deeper look. Your explanation makes sense - this is one of the regions with the strongest associations so I'm not surprised to see so many signals. I can certainly close the original issue #122 but I think you opened this one, so I can't close it.

**Comment by stephens999** [comment]
Thanks!
