### ISSUE TITLE
Confusion regarding the interpretation of output from confidence sets

### ISSUE THREAD

**Issue by ZayedShahjahan373** [stephenslab/susieR#130]
Hi, 

I hope you are all doing well. I am working on a genetic fine-mapping project with simulated data and so far the susie function has performed as expected. I do have a question about the variable names returned by the 'sets' accessor. 'susie.mod$sets' returns a set of numbers that do not correspond to any of my variables in the matrix of SNVs; which are all labelled in this 'rsXXXX' style. Am I correct interpreting these numbers in the confidence set as the index positions of the columns in the SNV matrix? 

Thank you,
Zayed Shahjahan

**Comment by gaow** [comment]
@ZayedShahjahan373 yes those are indices of variables. You can configure it to match the genomic coordinate using `pos`. See `?susie_plot` for details. But the function cannot label x-axis with rsID or any non-integer labels.

**Comment by ZayedShahjahan373** [comment]
Thank you Dr. Wang. Much appreciated.
