### ISSUE TITLE
fine-mapping of GWAS from case-control data?

### ISSUE THREAD

**Issue by kousathanas** [stephenslab/susieR#136]
Can the summary statistics approach (susie_rss) be used for analysing summaries from case/control data ? I.e., summaries from logistic regression?

**Comment by kousathanas** [comment]
Specifically for GWAS summary outputs

**Comment by gaow** [comment]
@kousathanas we have performed some simulation and it seems to work well for the settings we looked at, although we did not assess formally all scenarios eg a large range of multi-SNP effect sizes and case/ctrl ratios. We also used it for some case/ctrl GWAS that seems to produce good results consistent with findings from previous studies. We believe it warrants a go on your data.
