### ISSUE TITLE
Order of input

### ISSUE THREAD

**Issue by katherinef** [stephenslab/susieR#138]
Hello,

I am using susie_rss for genetic fine-mapping:

> susie_rss(z_scores, cor_matrix.cor)

where z_scores is a vector of z scores from logistic regression and cor_matrix.cor is a correlation matrix of the genotypes of 1,170 variants (always in the same order as the z scores vector).

The issue is that the results do not seem to be robust to the order of variants in the two files.  If I remake the input files with the variants in a different order I get a different number of credible sets and different variants within the sets.

Do you know why this might be and whether the results can be made to be the same irrespective of order?

Best wishes,

Kath

**Comment by stephens999** [comment]
that is weird -- I think  the order should not matter. Can you give a reproducible example?

**Comment by katherinef** [comment]
My apologies - it was my reordering that was the problem, not Susie.
Thanks for your response!
Kath
