### ISSUE TITLE
Is it possible to do whole genome analysis with susieR?

### ISSUE THREAD

**Issue by garyzhubc** [stephenslab/susieR#139]
I'm a researcher interested in reading deeper about susieR, especially the part of with summary statistics based on Zhu's paper. I saw that in the paper of susieR you used it for fine-mapping, but is it possible to do whole genome analysis with susieR by computing z-score and LD-matrix with PLINK2 and plug that into `susie_rss`? I think in my case, the LD-matrix will be huge. Is there an upper-bound on `L` to specify, given that the paper suggests the program is not sensitive to overstating `L`, but the paper reports convergence issues with many effect variables? I saw that in one vignette you used L0Learn to initialize susieR, but given my dataset is too big, do you recommend any other program? Just out of curiosity, although not directly relevant to my use, what is the purpose of having two different sets of input into `compute_suff_stat`, either `XtX`, `XtY`, `ss(y)` and `yty` or `n`, `b_hat`, `bhat`, `shat`, `cov(X)`, and `y`, and will the results from this be different from `susie_rss`? If so, in what sense might they be different? There's an option to set `refine=TRUE` with additional computation overhead, but can one still access convergence on real data after fitting a non-refined model? The vignette isn't clear about the algorithm for refinement, especially that the variables are undefined such as `s`, `mu`, and `alpha`, so what's the logic behind refinement? What's the rationale of whether to standardize my data, or is this not very important, because I don't think it's very clear from the paper besides for impacting whether to scale prior variance accordingly? Is there any datasource that you recommend for setting informative prior weights, besides for another GWAS in a study of a similar or highly related outcome? My question is quite long but I appreciate your response.

**Comment by gaow** [comment]
susie_rss preprint https://www.biorxiv.org/content/10.1101/2021.11.03.467167v1 @garyzhubc
