### ISSUE TITLE
Get NA value by function "compute_colSds"

### ISSUE THREAD

**Issue by mushanliw** [stephenslab/susieR#142]
n <- 10000; a <- rep(0.01012876, n); b <- rep(-0.00020425, n)
X <- cbind(a, b)
(colSums(X^2)/n - (colSums(X)/n)^2)*(n/(n-1))

_a             b 
-1.355388e-20 -6.618107e-24_ 

sqrt((colSums(X^2)/n - (colSums(X)/n)^2)*(n/(n-1)))

_a   b 
NaN NaN 
Warning message:
In sqrt((colSums(X^2)/n - (colSums(X)/n)^2) * (n/(n - 1))) : NaNs produced_

That's because of the computation numerical problem, I suggest the build-in function **sd**.

**Comment by gaow** [comment]
@mushanliw This issue has been fixed in the `master` branch. A cran release is being reviewed and will be updated once it passes review.
