### ISSUE TITLE
High PIP but not in credible sets

### ISSUE THREAD

**Issue by katherinef** [stephenslab/susieR#144]
Hello,

I have run susie_rss for a large region and obtain two credible sets.  When I plot the PIPs I notice there are a number of variants with high PIPs but that are not in either credible set (see attached).  I looks to me like there should be a third credible set.  Do you have any suggestions for what I might try?

Many thanks,

Kath
![susieplot](https://user-images.githubusercontent.com/5477560/140919674-9f5c1aaa-a658-44e9-9193-853ed214b372.png)

**Comment by gaow** [comment]
@katherinef I assume you are referring to the variables around position 7000. In order for variables to be in a `rho` credible set, their PIP have to sum to greater than or equal to `rho`, and their "purity", defined by minimum absolute pairwise correlation, should be greater than or equal to `r`. Currently, `rho` is set to 0.95 and `r` is set to 0.5. You can lower either these numbers, or both, to be more lenient with credible sets, depending on your analysis context (current default is what we believe reasonable for genetic fine-mapping applications)

**Comment by katherinef** [comment]
Thank you very much - that's really helpful.
