### ISSUE TITLE
Run susieR on QTL datasets

### ISSUE THREAD

**Issue by Al-Murphy** [stephenslab/susieR#150]
Hi, thank you for a great package!  I was wondering if susieR can be run directly on QTL datasets (e.g. transcription factor QTLs - tfQTLs) rather than using summary statistics from GWAS? My apologies if this is an obvious thing I'm missing!

Thanks!

**Comment by gaow** [comment]
@Al-Murphy we have not analyzed tfQTL in particular, but `susie()` function will take the full data assuming `y` the phenotype is Gaussian. Perhaps you could take a look at `?susieR::susie` and see if that's helpful?

**Comment by Al-Murphy** [comment]
Hey @gaow thanks for the quick reply! The ?susieR::susie help file is useful but it isn't intuitive to me how to go from a QTL sumstats file to performing an analysis with susie using it. 

These QTLs files are all generally in the same format (hQTLs, eQTLs etc), is there any documentation on how to input these to susie? The QTL sumstats file looks like this if that helps at all:

```
           chr.pos_ref_alt    rsid      phenotypeID p.value     beta Bonferroni.p   lFDR    alt.AF        se Eigen.p
        1:    3:66_C_A  rs1234  3:1234:1245 0.11340 -0.20740            1 0.2478 0.7588830 0.1310093       1
        2:    2:66_G_C  rs5678  2:1234:1245 0.05122 -0.25590            1 0.1835 0.7664970 0.1312555       1
        3:    9:66_T_A  rs9123  9:1234:1245 0.06678 -0.23970            1 0.2027 0.7538070 0.1307584       1
        4:    7:66_C_G  rs4567  7:1234:1245 0.02073 -0.29400            1 0.1202 0.7182740 0.1271150       1
        5:    10:66_C_T rs8912  10:1234:1245 0.09213 -0.21660            1 0.2249 0.7436550 0.1286019       1
```

**Comment by gaow** [comment]
@Al-Murphy oh I see, you are still going to use summary statistics. I was wrong to assume you use full data for QTL studies. In that case, you can derive z-scores from p values and beta, eg, look for `ConvertP2Z` function on this page: https://github.com/stephenslab/gtexresults/blob/master/workflows/fastqtl_to_mash.ipynb so you get the z-score input for `susie_rss`. You'll then have to find the matching LD reference matrix and run `susie_rss` as you would do for GWAS summary statistics applications.
