### ISSUE TITLE
"Prior variance is unreasonably large" and admixed samples 

### ISSUE THREAD

**Issue by ttumkaya** [stephenslab/susieR#159]
Dear susieR developers,

Thank you for making this tool available to the scientific community. 

I have been using susieR to fine-map eQTL signals in ~1000 loci, and the runs fail at ~800 of them with the error message that has been reported here several times: "The estimated prior variance is unreasonably large. Please check the input.". I'm specifically using the `susie_rss` function and using summary statistics, where LD matrix is calculated from the 1KG data for the appropriate ancestries. 

Following the suggestions made to the similar posts, I have made sure that there was no allele switch issues. Using the genotype matrix itself to calculate in–sample correlations in R also did not solve the problem. 

I have compared the datasets for the successful ~200 runs and ~800 failed runs to see if there are any obvious reasons that could explain the error. For example, I have compared z-score and LD matrix value distributions, number of variants, size of the loci, chromosomal location, number of significant variants in the region etc. There are no discrepancies between the datasets for successful and failed runs. One interesting observation was that both successful and failed runs had a wide-range of `s values`, where datasets with high s-values were run with no errors in some cases, as well as datasets with low s-values giving errors. (see the attached violin plot).

What I think might be the problem at this point is that 1) the eQTL data were derived from ~40 samples, and that could be a limitation of the small sample size, 2) the samples are from a mix of AFR and EUR ancestries, and that somehow might be causing a mismatch between the LD matrix and z-scores (I have tried using only EUR or AFR reference panels, as well as merged AFR+EUR panel).

As a side note, I'm also fine-mapping GWAS signals for the same loci (with the intention of doing a co-localization analysis later), which is also derived from individuals with EUR and AFR ancestry, and getting the same error for a large number of runs.

In the end, I've decided to proceed with the `check_prior ` flag set to FALSE for both the eQTL and GWAS signals, and take the results with a grain of salt.

I am curious to know your thoughts about the error and/or the decision of not checking prior in the analysis stage, and would really appreciate any feedback you might have.

Best,
Tayfun

[s_val_violin.pdf](https://github.com/stephenslab/susieR/files/8532421/s_val_violin.pdf)

**Comment by pcarbo** [comment]
@ttumkaya Could you elaborate on this statement, "Using the genotype matrix itself to calculate in–sample correlations in R also did not solve the problem"? Afterward you say: "The samples are from a mix of AFR and EUR ancestries, and that somehow might be causing a mismatch between the LD matrix and z-scores." But if you computed the LD matrix properly there should be no mismatch.

Regarding the samples with different ancestries you might try first running susie separately on the AFR or EUR samples, or find a way to control for population structure in your analysis (other fine-mapping papers may have advice on how to do this).

40 samples is not a lot and this may limit your fine-mapping analysis.

**Comment by ttumkaya** [comment]
Thank you for the prompt response @pcarbo What I mean by that is that I get the same error message even after calculating the correlation matrix by using the genotype data in R. I'd be happy to share a sample file via email if it'd help to reproduce the error. 

When I don't use the genotype data, I use PLINK 1.9 to compute the LD matrix from 1KG AFR and EUR samples combined, using `plink --bfile $1KG_panel --r square yes-really --extract $variants --write-snplist --out $output`. 

As for controlling for population structure, that's definitely something I can try. But shouldn't using the in-sample correlation matrix or an LD matrix from appropriate ancestries work in susieR?

Thank you,
Tayfun

**Comment by pcarbo** [comment]
Currently susieR doesn't have a way to include covariates but you could "correct" for an ancestry covariate by modifying X and y using the `remove.covariate.effects` function [here](https://github.com/pcarbo/varbvs/blob/master/varbvs-R/R/misc.R).

**Comment by ttumkaya** [comment]
Thanks for the tip @pcarbo , will give it a try.

Best,
Tayfun

**Comment by gaow** [comment]
@ttumkaya could you update to the current `master` of susieR? the susie_rss function now accepts sample size parameter `n` and with that, as well as in-sample LD, the math should be identical to as if you use the original genotype and phenotype data. Even without the update, the fact that check_prior identifies discrepancy using in-sample LD still puzzles me but I agree with @pcarbo that there is a small chance that population structure can cause this (assuming your summary statistics were computed accounting for population structure but these covariates were not regressed out of your genotype matrix).

**Comment by ttumkaya** [comment]
Thanks for the insights @gaow. Indeed, updating to the version 0.12.6 and including the sample size parameter have helped with most loci. You and @pcarbo also have a good point about the population structure, the summary statistics were computed with accounting for them, while the genotype matrix was not. 

Thank you both for your help, much appreciated!
Tayfun
