### ISSUE TITLE
Record number of iterations as a debug message

### ISSUE THREAD

**Issue by gaow** [stephenslab/susieR#17]
It is most straightforward to add [under this line](https://github.com/stephenslab/susieR/blob/53a521ec909dbb988c077a1ba2f92f6424e476a5/R/susie.R#L123) the following:

```
s$n_iter = i
```
so that I can keep the number of iterations for my own reference. I guess this is a style question : may I do that, or should it be in some `debug` variable?

**Comment by stephens999** [comment]
Do that for now. If you want to be safe add a susie_get_niter function too, and use susieR::: to access. Then we can decide on internal storage issues and whether to export etc later.
