### ISSUE TITLE
Large number in lbf_variable matrix

### ISSUE THREAD

**Issue by hbliu** [stephenslab/susieR#178]
Thank you very much for this amazing tool SusieR. I exported the lbf_variable matrix. However, I found very large values (>10,000) in this matrix.

![image](https://user-images.githubusercontent.com/2704756/209388340-cf3e9256-77b0-4d9b-b06a-85b67d6d5721.png)

Would you please help fix this issue?
Data and code are available at https://www.dropbox.com/s/204sg2ryo17u38t/ExampleData.zip?dl=0.

Thank you. 

Related to #109

**Comment by pcarbo** [comment]
@hbliu Are the association p-values for these SNPs (e.g., calculated using PLINK) also very small? If so, this would suggest that these are just very strong associations.

In any case for fine-mapping we typically focus on the PIPs and the credible sets (CSs), not the Bayes factors.

**Comment by stephens999** [comment]
Are you using in sample ld? This kind of thing could be caused by use of an out of sample ld matrix that does not match in sample well enough

**Comment by pcarbo** [comment]
Excellent. You might also find the "kriging_rss" function to be useful.
