### ISSUE TITLE
Credible set is a set of SNPs with the lowest p-value

### ISSUE THREAD

**Issue by PhoebeGuo97** [stephenslab/susieR#180]
Hello, I run susie_rss for one interested locus with ~1000 SNPs. It converged and lambda was ~0.19. There is one CS with 15 SNPs in the output (see below) and these 15 SNPs are also the SNPs with the lowest p values in that region. I'm wondering if that's suspicious. Thanks!

> rss$sets$cs
$L1
 [1] 497 515 538 540 889 898 903 919 923 925 928 932 976 978 981

**Comment by pcarbo** [comment]
@PhoebeGuo97 Quite the opposite, that sounds like the right result.
Can you share the full `rss$sets`?

**Comment by PhoebeGuo97** [comment]
Hello @pcarbo, here is the full rss$sets:

$cs
$cs$L1
 [1] 497 515 538 540 889 898 903 919 923 925 928 932 976 978 981


$purity
   min.abs.corr mean.abs.corr median.abs.corr
L1    0.7630299     0.8993411        0.955967

$cs_index
[1] 1

$coverage
[1] 0.9513883

$requested_coverage
[1] 0.95

**Comment by pcarbo** [comment]
Those results look reasonable — I don't see any cause for concern.

**Comment by PhoebeGuo97** [comment]
Good to know. Thank you!
