### ISSUE TITLE
Repo License?

### ISSUE THREAD

**Issue by carlaost** [stephenslab/susieR#183]
Hi!
I am unable to see a license attached to this repo. I'd love to include it in a publication I am building on nodes.desci.com but am unsure whether this is within the terms. Would be great to get some clarity on this! 
Thanks!

**Comment by pcarbo** [comment]
@carlaost We are using the BSD 3-clause license:
https://github.com/stephenslab/susieR/blob/master/LICENSE

**Comment by carlaost** [comment]
great, thanks!
