### ISSUE TITLE
fine-mapping with BOLT-LMM GWAS summary statistics

### ISSUE THREAD

**Issue by xliaoyi** [stephenslab/susieR#199]
Dear SuSiE Team,

Thanks for developing such a fantastic package and for the rigorous statistical work that underpins it. 

I have a question about using SuSiE for fine-mapping with GWAS summary statistics generated by BOLT-LMM. When I run diagnostics using a matched LD matrix, I notice that the observed z-scores are not perfectly correlated with the expected z-scores. I suspect this discrepancy may be due to the covariates I included in the BOLT-LMM analysis. In light of this, can the fine-mapped credible sets still be considered reliable?

Here is the diagnosis plot:
![kriging_rss_plot](https://github.com/stephenslab/susieR/assets/53245028/3dccf1fb-4ce3-4653-ac25-d01d79490cf1)

Here is my code:
```
library(susieR)
library(tidyverse)

set.seed(1)

ld_matrix <- read.csv("SUSIE_OUTPUT/susiex_both/test_ld_matrix.ld", sep = '\t', header = F)
ld_matrix <- as.matrix(ld_matrix)

# get phenotype data
pheno <- read.csv("GWAS_INPUT_DATA/hip_select_pheno_gwas_cm_230713.txt", sep = " ")

# get filtered gwas sumstats
sumstats <- read.csv("CODE/SUSIE_CODE/filtered_gwas_sumstats.txt", sep = "\t")
z_scores <- sumstats$BETA / sumstats$SE
susie_plot(z_scores, y = "z")

res <- kriging_rss(z_scores,ld_matrix)
plot(res$plot)

lambda = estimate_s_rss(z_scores, ld_matrix, n=30324)

fitted_rss1 <- susie_rss(bhat = sumstats$BETA, shat = sumstats$SE, n = 30324, R = ld_matrix, var_y = var(pheno$pelvic_inlet_width), L = 10,
                         estimate_residual_variance = TRUE)

summary(fitted_rss1)$cs
susie_plot(fitted_rss1, y="PIP")
```

Your tutorial suggests that using individual-level data yields better results than summary statistics. I am interested in exploring this approach but am unclear about the structure of the genotype matrix as described in your tutorial. Is it a matrix with patient IDs as row names, SNPs as column names, and filled with values 0, 1, or 2 to indicate the genotype? If so, how should I handle missing values in this matrix? Additionally, should I first residualize the phenotype y using the same covariates that were included in the BOLT-LMM analysis, given that the lead SNPs are derived from BOLT-LMM results?

I look forward to your guidance on these matters.

Best regards,
Liaoyi

**Comment by pcarbo** [comment]
> I suspect this discrepancy may be due to the covariates I included in the BOLT-LMM analysis.

We haven't systematically studied the use of LMM summary statistics in susie, but it might help to instead use the LD matrix that "corrects" (removes the linear effect of) the covariates.

**Comment by xliaoyi** [comment]
> > I suspect this discrepancy may be due to the covariates I included in the BOLT-LMM analysis.
> 
> 
> 
> We haven't systematically studied the use of LMM summary statistics in susie, but it might help to instead use the LD matrix that "corrects" (removes the linear effect of) the covariates.

Thanks for your prompt reply! May I ask is there any software can generate such LD matrix which has covariates corrected? The LD matrix I am using was generated by plink.

**Comment by stephens999** [comment]
Is it a matrix with patient IDs as row names, SNPs as column names, and filled with values 0, 1, or 2 to indicate the genotype? 

Yes

If so, how should I handle missing values in this matrix? 

Impute missing genotypes using impute, beagle etc

Additionally, should I first residualize the phenotype y using the same covariates that were included in the BOLT-LMM analysis, given that the lead SNPs are derived from BOLT-LMM results?

Probably a good idea yes

**Comment by yu-zhang-oYo** [comment]
> > > I suspect this discrepancy may be due to the covariates I included in the BOLT-LMM analysis.
> > 
> > 
> > We haven't systematically studied the use of LMM summary statistics in susie, but it might help to instead use the LD matrix that "corrects" (removes the linear effect of) the covariates.
> 
> Thanks for your prompt reply! May I ask is there any software can generate such LD matrix which has covariates corrected? The LD matrix I am using was generated by plink.

Hi, the manual said "it is recommended that the “in-sample” LD matrix also be computed from the genotypes after the covariate effects have been removed." I used mixed model for a binary outcome, I would like to know if what is the consequence if I just simply calculate the LD with the individual genetic data and then use it in the susie_rss. Is there any software that can correct the covariates or the random effect in the mixed model?

Is there any way to consider the binary outcome and random effect in the individal genetic data, like the susie?

Thanks

**Comment by pcarbo** [comment]
@yu-zhang-oYo For binary outcomes, our experience — noting we have not published results on this — is that it is better to use a linear regression for the binary outcome, not a logistic regression. 

I believe Issue #82 is relevant to your question about removing covariates from the LD matrix.

For using summary statistics from an LMM-based analysis, it is less clear if this is a good idea. This has also been discussed in other Issues, e.g., Issue #168. I believe [SuSiE-Inf](https://doi.org/10.1038/s41588-023-01597-3) might work with LMM-based summary statistics; I would check their paper.
