### ISSUE TITLE
Automatically choose `L`

### ISSUE THREAD

**Issue by gaow** [stephenslab/susieR#20]
Currently we compute results for every of `1 ... L`. Would it be helpful to set it `maxL` instead and be able to stop if computed alpha posterior deviates little from prior? What would be the stopping criteria?

This is actually also related to #19 : we can apply both purity filter and this filter? and see how much they agree?

**Comment by stephens999** [comment]
i've experimented a bit with this. conclusion was that it was not that easy
to have a robust approach.
it is related to the `susie_auto` function.  don't think we need it for
fine mapping really, so not a priority.

**Comment by gaow** [comment]
Maybe results in [this notebook](https://gaow.github.io/mvarbvs/analysis/20180709_SplicingQTL_Detailed.html) might motivate this in the context of fine-mapping? Although a simple filter of `L` would not suffice.

**Comment by gaow** [comment]
This ticket and #8 are both related to #2 . @pcarbo and I have discussed in person a possibility similar to what `varbvs` has done, which is essentially another version of `susie_auto` (not yet implemented). As shown in the notebook above, this might be relevant to fine-mapping application already. I'll close this ticket and we can use #2 for more discussions.
