### ISSUE TITLE
How to get regression coefficients from susie?

### ISSUE THREAD

**Issue by garyzhubc** [stephenslab/susieR#210]
I'd like to know whether my variants is positive or negatively related to a phenotype. How can I assess this from susieR?

**Comment by garyzhubc** [comment]
Or, a set is positive or negatively related.

**Comment by garyzhubc** [comment]
Right now I'm using:
```
susie_plot(sus, x="index", y="PIP", b = (sus$pip)>0.6 & apply((sus$mu>0)[apply(sus$alpha, 2, which.max),],2,max))
```

Is it reasonable?

**Comment by gaow** [comment]
For coefficients you should use `coef(fitted)` where `fitted` is the output of susie() or susie_rss()
