### ISSUE TITLE
What is the variational family q_l of equation (3.7)? Is this the only difference from spike-and-slab regression of Carbonetto et al. 2012?

### ISSUE THREAD

**Issue by garyzhubc** [stephenslab/susieR#214]
What is the variational family q_l of equation (3.7)? Is this the only difference from spike-and-slab regression of Carbonetto et al. 2012?

**Comment by gaow** [comment]
@garyzhubc As a brief comment, (3.7) is definitely a key difference from Carbonetto et al 2012, but I would say that the higher level "sum of single effect" model setup is the most distinctive feature of our model.

As previously indicated, this platform is specific for susieR software related discussions. For general questions regarding the manuscript we suggest you discuss it through other channels or with other colleagues.
