### ISSUE TITLE
How to get Fig 3 from Susie (as a frequentist procedure)? 

### ISSUE THREAD

**Issue by garyzhubc** [stephenslab/susieR#232]
I'd like to reproduce the coverage, power, median size, and average squared correlation in Fig 3. What option should I use? What is the null hypothesis? Is it the same as "null simulations"? What is the test statistic?

**Comment by pcarbo** [comment]
@garyzhubc Please take a look at [this github repository](https://github.com/stephenslab/susie-paper/) which contains the code used to generate the results in the SuSiE paper. See for example [this analysis](https://stephenslab.github.io/susie-paper/manuscript_results/numerical_results.html).
