### ISSUE TITLE
whys the results of fitted_rss1$sets$cs  is less than susie_get_cs(fitted_rss1) 

### ISSUE THREAD

**Issue by koujiaodahan** [stephenslab/susieR#233]
for exmaple:
<img width="1366" alt="image" src="https://github.com/user-attachments/assets/d8cf89ac-ef31-49c1-9f08-71d818e9725b">

so, whats the reason for the difference, the purity setting?

**Comment by pcarbo** [comment]
Yes, I believe so. If I remember correctly, if you do not provide X in susie_get_cs(), it will not filter out CSs based on purity.
