### ISSUE TITLE
Approximation families

### ISSUE THREAD

**Issue by garyzhubc** [stephenslab/susieR#235]
What are the variational approximation families of the PIPs? It doesn't seem to have been mentioned in the paper. It just mentioned that it's better than BVSR.

**Comment by gaow** [comment]
@garyzhubc as discussed previously, please kindly limit your inquires to software related questions in this repo, and data/simulation related issues to the [SuSiE paper repo](https://github.com/stephenslab/susie-paper). Please use other means of communication or resort to other local sources for more general queries such as these. Thanks for your understanding!
