### ISSUE TITLE
`susie_get_CS` takes long time for large number of variables

### ISSUE THREAD

**Issue by gaow** [stephenslab/susieR#24]
For an application of up to 50K variable selections with `L=15`, `susie_get_CS()` takes one hour to filter by purity. What might be time consuming are these lines:

1. [compute xcorr](https://github.com/stephenslab/susieR/blob/e584cb32bb7ad784a398dfda388318823e233079/R/susie_utils.R#L83)
2. [extract purity from xcorr](https://github.com/stephenslab/susieR/blob/e584cb32bb7ad784a398dfda388318823e233079/R/susie_utils.R#L93)

@pcarbo do you see any obvious issues with my R coding that we can speed up with minor changes?

An obvious speed up is to add a `max_size` filter that removes very large CS regardless of purity. We can set the default to removing, say, CS of size greater than `0.5*P`?

**Comment by stephens999** [comment]
you should first compute all CS's, and then compute the purity of each,
computing cor only for variables in each CS.
You don't need to cor for variables not included in any CS!

**Comment by stephens999** [comment]
hmm, ok I see now that you are doing this as there will often be at least
one very large CS!
So you would have to filter in some way.

How about randomly sampling 100 elements from each CS first and removing
any that do not pass filter?
THat way you will only compute 100 by 100 matrices

**Comment by gaow** [comment]
@stephens999 yes that should do the trick, thanks!
