### ISSUE TITLE
IBSS algorithm did not converge 

### ISSUE THREAD

**Issue by kuaileshizuihao** [stephenslab/susieR#240]
Dear SuSiE creators:
Thank you for developing such a useful algorithm. I encountered the following issues and had to seek help here.

I conducted a GWAS on my dataset, which included 2492 individuals. Following the GWAS, I used the Z-scores of 3238 variants within 500 kilobases of the most significant site, along with the in-sample linkage disequilibrium (LD) matrix, as input for the susie_rss function. The following situation arose. It looks the same as this problem. #176 

```
fitted_rss1 <- susie_rss(z= CleanSS$Z_STAT,
                         n = 2492, R = LDMatrix,
                         L = 5,
                         estimate_residual_variance = F)
# In susie_suff_stat(XtX = XtX, Xty = Xty, n = n, yty = (n - 1) *  :
# IBSS algorithm did not converge in 100 iterations!
#                Please check consistency between summary statistics and LD matrix.
#                 See https://stephenslab.github.io/susieR/articles/susierss_diagnostic.html

lambda  <-  estimate_s_rss(CleanSS$Z_STAT, LDMatrix, n=2492)
# WARNING: The matrix R is not positive semidefinite. Negative eigenvalues are set to zero
# lambda = 0.45
```

And This is the distribution of my z-score.
![zscore](https://github.com/user-attachments/assets/c711667c-9338-438b-8d55-2d06d4413279)

I noted that when I set "estimate_residual_variance = T", it hinted me that 
> HINT: For estimate_residual_variance = TRUE, please check that R is the "in-sample" LD matrix; that is, the correlation matrix obtained using the exact same data matrix X that was used for the other summary statistics. **Also note, when covariates are included in the univariate regressions that produced the summary statistics, also consider removing these effects from X before computing R.**
  Estimating residual variance failed: the estimated value is negative

When I conducted the GWAS, I adjusted for the effects of variants by including age, sex, and PC1-PC3 derived from genotype data as covariates.  Is this the cause of my problem? Does it mean that I should adjust for these covariates when computing the LD matrix. If that's the case, how should I implement it? 

Thank you very much!

**Comment by pcarbo** [comment]
@kuaileshizuihao If you computed an in-sample LD matrix, you should not have to use `estimate_s_rss()`. (However, it is helpful to use the kriging function to check your LD matrix.) 

"Removing" covariates from the LD matrix is discussed in Issue #82.

**Comment by kuaileshizuihao** [comment]
> @kuaileshizuihao If you computed an in-sample LD matrix, you should not have to use `estimate_s_rss()`. (However, it is helpful to use the kriging function to check your LD matrix.)
> 
> "Removing" covariates from the LD matrix is discussed in Issue #82.

Thank you so much!!!! I'll try it.

**Comment by yu-zhang-oYo** [comment]
Hi, have you find the reason for this error? I met the same phenomenon as this, but I thought that the in-sample LD matrix would not cause the red dot in the plot of the distribution of  z-score.

**Comment by kuaileshizuihao** [comment]
I get my GWAS summary statistics using PLINK. By default, it selects the effect allele based on the MAF. After setting the ALT ellele as the effect allele, the issue was resolved. I hope this helps for you! 
        
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        2/4/2025 05:38
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Haijie ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [stephenslab/susieR] IBSS algorithm did not converge (Issue #240)
        
      
    
  

Hi, have you find the reason for this error? I met the same phenomenon as this, but I thought that the in-sample LD matrix would not cause the red dot in the plot of the distribution of  z-score.

**Comment by pcarbo** [comment]
Thank you for sharing @kuaileshizuihao.

Here is some info about PLINK2 from one of my collaborators that might also be useful:

> It seems like the default in plink 2 for the ld computation is to use dosage of the major allele https://www.cog-genomics.org/plink/2.0/ld, while using the omit-ref modifier for association testing uses dosage of the alternate allele (https://www.cog-genomics.org/plink/2.0/assoc). So to get consistent ld matrix + summary state you would want to use the ref-based modifier for the ld call.
