### ISSUE TITLE
A SuSiE data type

### ISSUE THREAD

**Issue by gaow** [stephenslab/susieR#30]
So separated from #27 I wanted to suggest a SuSiE data object now that we have the sparse branch coming. Something along the lines of `mash_set_data()` results. I was trying to design it but not happy with what I come up with because I keep thinking along the lines of class methods and other OOP conventions. I think the discussion might become more concrete when @KaiqianZhang sends in the new pull request (we are still simplifying it)

**Comment by pcarbo** [comment]
@gaow That's a great idea. It is as simple as doing something like

```R
class(out) <- c("susie","list")
```

and then providing careful documentation about this class.

**Comment by gaow** [comment]
I think we are in the position to revisit this, now that we've finalized the sparse branch. I see there is a need to unify the susie data object to summary statistics version. As have expressed before I have my hesitations.  Need to think more about it (and read more) and work with @zouyuxin. If anyone knows good examples of customized R objects please tip me!

**Comment by pcarbo** [comment]
@gaow Start with the output of `lm`. Most customized R objects (I would say >95%) are just lists with a class attribute.

**Comment by stephens999** [comment]
And I suggest keeping it simple like this.
Indeed, I think we already have a Susie object type like this here, don't
we?

**Comment by gaow** [comment]
> And I suggest keeping it simple like this.

Okay we'll not got for OOP in S4.

> Indeed, I think we already have a Susie object type like this here, don't we?

We do. And we need to have operators over these objects -- set data and convert data. These operators should be able to take full data and several types of summary statistics.

**Comment by stephens999** [comment]
i'm not quite sure what we are trying to achieve here...a "data" object or
a "fit" object, or....

in mash the reason we introduced a data object is that we often have to do
multiple steps
on the same "data", and it is convenient to have a single data object to do
this on.

But in susie, a lot (most?) analyses are just a single step? If that is
true I'm not sure we need
a "data" object (eg to contain Y and X). At least, not one that users need
to worry about....

**Comment by gaow** [comment]
@stephens999 I guess we can talk in person about this, but for the moment I'm not going to make drastic changes, just trying to improve things under the current framework.
