### ISSUE TITLE
compute_ss function

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/susieR#48]
@zouyuxin I was thinking it would be useful to have a function, something like `compute_ss(X, y, standardize = TRUE)`, to compute the summary statistics from the "raw" data. The summary  statistics computed would be the first 3 or 4 arguments to `susie_ss`. This would greatly simplify the code and reduce errors.

**Comment by zouyuxin** [comment]
@pcarbo the summary statistics version is aimed to be applied with betahat, var(y), or z scores, and LD or correlation matrix(`XtX`). So there is no individual level data. `Xty` should be derived from the summary statistics.

**Comment by pcarbo** [comment]
I understand, but sometimes it is useful to be able to compute summary statistics from the raw data (e.g., for testing).

**Comment by zouyuxin** [comment]
@pcarbo I added the function `compute_ss`, and change the example in `susie_ss`

**Comment by pcarbo** [comment]
@zouyuxin Thanks! Don't forget to re-run `devtools::document()` after updating roxygen2 syntax.
