### ISSUE TITLE
Implement `summary` function

### ISSUE THREAD

**Issue by gaow** [stephenslab/susieR#52]
As mentioned in passing in #36, function `summary` can now be applied to a susieR fit to get more concise / polished output. The idea is that by default users should only need to run `susie()` then use `coef`, `predict` and `summary` to access all information they need. Plus perhaps additionally `susie_plot()`. In other words we might want to mimic how `lm` behaves.

I have already implemented a version of `summary`, to be demonstrated in upcoming vignettes. We can add more to it as we see fit.

**Comment by pcarbo** [comment]
@gaow Your summary function is a good start. A couple suggestions:

+ Make sure it has the same argument names as the default summary function, `summary(object, ...)`.

+ By convention, the result should be class `c("summary.susie","list")`, and then you should have a separate `print.summary.susie` function to turn this output into a nice, printable summary that ideally is short (yet informative!). Ideally, the output of `summary.susie` should also be fairly concise (hence, "summary"). See `summary.varbvs.R` in my `varbvs` package for an illustration of this.

**Comment by gaow** [comment]
@pcarbo good suggestions particularly on the `print` pointer. I'll keep this ticket open to revisit.
