### ISSUE TITLE
New interface for summary statistics version

### ISSUE THREAD

**Issue by gaow** [stephenslab/susieR#53]
@zouyuxin although we have discussed it in person, from my experience it is always best to open new issues for new features added to keep everybody in the loop even if we do not need to discuss it with others. We then close the issue only when the feature is documented and added to unit tests. Tickets helps us keeping track of development.

Yuxin and I have currently agreed to support 3 main susie function calls:

1. `susie`, with input `X`, `Y` etc (already implemented).
2. `susie_z`, with input `Z` and `R` where `R` is correlation. (we might optionally take var(Y) and sample size -- still working on it)
3. `susie_ss`, with input `betahat`, `sebetahat`, `varY`, `N` and `R` where `N` is sample size and `R` can be correlation, covariance or `X^TX`.

The old `susie_ss` interface which takes X^TX, X^Y, etc, will be made an internal function. 

Yuxin is working on the implementation now. We can discuss some more when she has the first draft of interface implemented and documented.

**Comment by pcarbo** [comment]
@gaow Thanks for the summary! Is `susie_z` also working with summary statistics then? Maybe we should call the functions `susie_ss_z` and `susie_ss_beta`, or something like that?

**Comment by gaow** [comment]
Sure. Our initial thought was `susie_z` and `susie_bs` but the latter is apparently not good. @stephens999 do you have other suggestions or we use what @pcarbo proposed?

**Comment by stephens999** [comment]
maybe _bhat?
