### ISSUE TITLE
get_objective

### ISSUE THREAD

**Issue by stephens999** [stephenslab/susieR#55]
i note that this is currently exported. But... it is not properly documented,
and further it is not clear if it is useful as the objective does not match the fit.
```
set.seed(1)
x = matrix(rnorm(100),nrow=10)
y = rnorm(10)
s = susieR::susie(x,y,2,verbose=TRUE)
susieR::susie_get_objective(x,y,s)
```
yields
```> s = susieR::susie(x,y,2,verbose=TRUE)
[1] "objective:-13.9178013824705"
[1] "objective:-13.9168870676643"
[1] "objective:-13.9153089047561"
[1] "objective:-13.9153086197788"
[1] "objective:-13.9153019958165"
[1] "objective:-13.9153019848613"
> susieR::susie_get_objective(x,y,s)
[1] -14.68734
```

**Comment by stephens999** [comment]
possibly because internally we are using a different x?

**Comment by gaow** [comment]
Yes at least we center and scale it internally. Any reason to better document and export it? I think `verbose` is enough for it.

**Comment by stephens999** [comment]
well it is already exported.
we could stop exporting...
