### ISSUE TITLE
susie_get_objective

### ISSUE THREAD

**Issue by stephens999** [stephenslab/susieR#58]
I think we should add this as an accessor function to the final elbo achieved

**Comment by gaow** [comment]
@stephens999 are you suggesting adding:

```r
susie_get_objective = function(s) {
  s$elbo
}
```

?

**Comment by stephens999** [comment]
no, only the last value, s$elbo[length(s$elbo)]

we could have an option to get the full vector.... but by default I'm just
interested
in the value obtained so we can easily compare fits from different
initializations.

**Comment by gaow** [comment]
@stephens999 Thanks for the suggestions -- both have been implemented.

**Comment by zouyuxin** [comment]
@gaow I have a susie fit with elbo at each iteration as `-Inf -1941.380 -1914.195 -1914.195`. The 3rd and the 4th elements are the same. `elbo[3] == elbo[4]` is TRUE. But `susie_get_objective` gives warning: `Objective is not non-decreasing`.

**Comment by gaow** [comment]
Sorry @zouyuxin it's an artifact of the patch from 3 days ago (see above). The patch below should have fixed it ...

```diff
 susie_get_objective <- function(res, all = FALSE, warning_tol = 1E-6) {
-  if (!all(diff(res$elbo) >= warning_tol)) {
+  if (!all(diff(res$elbo) >= (-1 * warning_tol))) {
     warning('Objective is not non-decreasing')
   }
```

**Comment by stephens999** [comment]
Can we close this?
