### ISSUE TITLE
How to do multi-enthnic fine-mapping?

### ISSUE THREAD

**Issue by gaow** [stephenslab/susieR#59]
I think this has been done before in the context of single effect model: basically combining the BF obtained before calculating PIP. This would work if the cross population causal variable is the same -- which should mostly be the case.

Potentially we can do the same for each SER update of SuSiE. Is there a problem for it? The code and interface might be a bit messy, though.

**Comment by stephens999** [comment]
i would suggest treating this a special case of the multivariate version (at least initially).
