### ISSUE TITLE
Add option to initialize variational parameters

### ISSUE THREAD

**Issue by jhmarcus** [stephenslab/susieR#6]
Add an argument in `susie()` and / or `susie_auto()` to take `alpha_init` as an argument. The use case is to initialize with the alpha using fast a best subset selection procedure i.e. implemented in https://github.com/hazimehh/L0Learn

**Comment by stephens999** [comment]
currently  susie can take a previous susie fit object as init.
so would it work to write a function that creates a suitable susie fit for a given alpha
that could then be used as s_init ?

**Comment by stephens999** [comment]
also do you really want to pass in alpha, or just a list of L "candidate" covariates to initialize at?
(corresponding to each row of alpha has one 1 and all others 0s, like 0000010000 )

**Comment by jhmarcus** [comment]
ah yes just looked a bit more closely at that.

**Comment by jhmarcus** [comment]
Ok so the previous "susie fit" is `s_init`. Ya I think a list of candidate covariates makes sense thanks!

**Comment by gaow** [comment]
@KaiqianZhang I think we should formalize & generalize your `L0Learn` initialization function -- I'm more talking about an interface. For example:

```
susie_set_initialization(pos, value=NULL, ...)
```

where `pos` is the index vector of non-zero effects to initialize `alpha`, and `value` is optional the effect size to initialize `mu`. We need to think of default behaviors for other `...` parameters.
