### ISSUE TITLE
lower case in function names

### ISSUE THREAD

**Issue by stephens999** [stephenslab/susieR#61]
I think upper case in function names is a pain. i forget which case we need.
suggest lower case:
susie_get_pip
susie_get_cs

**Comment by stephens999** [comment]
@gaow is this change going to cause any issues with your ongoing simulations etc?

**Comment by gaow** [comment]
Notice that the change will impact any existing projects (hopefully not too many) that uses these functions. Please fix them when you ran into the issue. At this point I do not think we should bother with backwards compatibility yet.
