### ISSUE TITLE
Summary version check R for positive semi-definite takes too much time

### ISSUE THREAD

**Issue by gaow** [stephenslab/susieR#65]
Currently we do eigen decomposition for the input `R` matrix and check for eigen values to ensure it is PSD. It is very time consuming. Should we check this at all? I think it is a good idea to check it. From a few data-sets I analyzed for others, their input R can be none PSD and susieR is able to capture that. So the question is how to check it more efficiently.

**Comment by stephens999** [comment]
what is PSD?

do you mean Positive semi-definite?
(this is a non-standard abbreviation)

**Comment by gaow** [comment]
@stephens999 Okay I've changed it. Maybe SPSD is a better abbreviation (at least I'm sure I've seen it in class)

**Comment by pcarbo** [comment]
The standard abbreviation is SPD = symmetric positive definite. I don't know of any other standard abbreviations.

**Comment by pcarbo** [comment]
@gaow In `mashr` we check that a matrix is SPD using `chol`. Would that work for your aims? I don't know if it is possible to distinguish (in finite-precision arithmetic) between positive definitive and positive semi-definite.
