### ISSUE TITLE
add examples for susie_trendfilter

### ISSUE THREAD

**Issue by stephens999** [stephenslab/susieR#68]
@KaiqianZhang can you add some simple examples to the documentation?

**Comment by KaiqianZhang** [comment]
sure!

**Comment by gaow** [comment]
I think this is done? 

https://github.com/stephenslab/susieR/blob/dc42e47ea5dd26c28a7be94ee2dc1dab8976eeae/R/susie_trendfilter.R#L7

I actually have updated [the vignette](https://github.com/stephenslab/susieR/blob/master/vignettes/trend_filtering.Rmd) to use the new interface, while reviewing the trendfiltering code.  But @stephens999 are you referring to additional examples?

**Comment by stephens999** [comment]
no this was it.
maybe we could add something like
plot(y)
lines(true_mean,col=1)
lines(predict(fit),col=2)
or similar to the first example to illustrate that one uses predict to
obtain the fitted values?

**Comment by KaiqianZhang** [comment]
Do you mean add these plot() to documentation?

**Comment by stephens999** [comment]
i mean to the example in @examples

**Comment by KaiqianZhang** [comment]
Sure! I just added it in the trendfiltering branch. You can see it from the
pull request.
