### ISSUE TITLE
improve specification of prior variance to be PVE?

### ISSUE THREAD

**Issue by stephens999** [stephenslab/susieR#8]
maybe it would be more interpretable to provide a typical PVE value instead of prior_variance?
(If x is not standardized we could average across x to get typical PVE).

but it is a bit complicated... there are obviosuly relationships between PVE, var(Y) and residual variance...

**Comment by gaow** [comment]
For my splicing QTL analysis I tried two approaches:

1. set prior based on averaged PVE estimated using top z-scored SNP for each analysis unit.
2. set prior per unit based on the PVE estimated using top z-scored SNP for that unit.

Using 1, I get a total of 2,343 loci with at least one signal, out of 77K analysis units (intron clusters). Using 2, I get a total of 3,038 loci with at least one signal for the same data-set.

BTW, as shown [in this notebook](https://gaow.github.io/mvarbvs/analysis/20180709_SplicingQTL_Detailed.html#SuSiE-with-L-=-5-but-estimated-prior-variance-125) using estimated prior variance instead (`estimate_prior_variance=TRUE`) mostly resolves the inconsistency between susie and CAVIAR. In fact it gives almost same result as with DAP -- top PIP > 0.6 versus CAVIAR's top PIP > 0.8.

**Comment by stephens999** [comment]
coming back to this after our conversation on Friday @gaow.

After thinking further I believe it would be better for the user to specify
the prior_variance parameter as scaled by the variance of Y (which is effectively known)
rather than scaled by the *residual* variance (which of course is unknown!).
That is, I think we should change the definition of the parameter prior_variance in the code
so the prior is b \sim N(0, prior_variance* var(Y))

Scaling by the residual variance -- as we do now -- is convenient algebraically, but it complicates prior specification (essentially by introducing a scaling factor that is unknown rather than known.)

**Comment by gaow** [comment]
Thanks @stephens999 . Yes I did not revert the change because I was thinking along the same line after our conversation -- basically I'm trying to reproduce the same behavior before commenting out that line, using larger prior specification (more over-estimates). I do find it is harder to think in terms of residual variance, even if some rough guesses of PVE is made beforehand. 

> can't push just yet due to authentication issues... but just wanted to let you know.

Thank you! But is there anything I can do with the authentication? I do not think I have the admin privilege to this repo but you should have, right?

**Comment by stephens999** [comment]
ok, I have pushed the changes. Can you take a look? 

The logic is supposed to be:

1. now internally all susie functions work with the actual prior variance (denoted by variable V) and the residual variance. Note V here is the actual prior variance, no scaling involved.

2. The user interface allows the user to specify V by specifying the parameter scaled_prior_variance, and then sets V= scaled_prior_variance*var(Y).
This is because generally sensible values of V will depend on var(Y). So I deemed it less likely to lead to confusion if users set scaled_prior_variance than to set V directly. 

In our simulations we would expect to set scaled_prior_variance about 0.1 (within order of magnitude).

Roughly speaking scaled_prior_variance is expected PVE

**Comment by stephens999** [comment]
ps, authentication issue was a problem my end.. now resolved.

**Comment by stephens999** [comment]
pps the only testing i did was to check that the unit tests pass. these are pretty minimal right now! it might be good to add some more...

**Comment by pcarbo** [comment]
> After thinking further I believe it would be better for the user to specify
the prior_variance parameter as scaled by the variance of Y (which is effectively known)
rather than scaled by the residual variance (which of course is unknown!).
That is, I think we should change the definition of the parameter prior_variance in the code
so the prior is b \sim N(0, prior_variance* var(Y)).

@stephens999 We have used the N(0,prior_variance * resid_variance) a lot in previous papers, so this is quite a significant change. What made you decide to make this change? Are you still aiming for a prior on the "prior_variance" parameter that can be framed in terms of PVE?

**Comment by stephens999** [comment]
First, note that if we estimate the parameters (eg by maximum likelihood, or maximizing elbo)
this change makes no difference. There are two  parameters to optimize over and the
exact parameterization does not matter.

Where it makes a difference is where one or other of the parameters is "fixed" to a user-specified value. In particular our default approach is to estimate the residual variance (s^2), but to let the user specify the "prior variance" for the non-zero effects   based on prior information about effect sizes b. It is much easier to specify a prior for b than a prior for b/s where s is unknown.

**Comment by pcarbo** [comment]
@stephens999 Thanks for the explanation. Yes, in that setting, that sounds like the right thing to do.

**Comment by gaow** [comment]
@stephens999 i've updated the [numerical study results](https://stephenslab.github.io/susie-paper/manuscript_results/numerical_results.html) with the redo prior branch. It is the same as with susieR version 0.1.x, as expected (prior variance remains unchanged in updates). But the logic is a lot clearer.

Should I merge it to `master` and bump the version to 0.3.0?

> pps the only testing i did was to check that the unit tests pass. these are pretty minimal right now! it might be good to add some more...

Kaiqian and I were discussing today about debugging via `browse` on basic units, which was exactly how she found a bug in her sparse branch. The current code on that branch still needs fixes but we are on the same page that these units (at least the ones that we had problems with!) should be properly included in unit tests. We'll do it tmr as they are still fresh in mind.
