### ISSUE TITLE
Compute posterior variance of effects

### ISSUE THREAD

**Issue by omerwe** [stephenslab/susieR#84]
Hi SuSiE,

I just started experimenting with SuSie and it looks very promising. I would like to ask about computing the posterior variance of effects. I couldn't find such functionality in the code. From my understanding of the math, the following code should do it. Can you please let me know if I got it right? (this assumes that the effects are conditionally independent given y and the posterior distribution parameters, hopefully this is right).

```
s = susie_bhat(bhat=bhat, shat=shat, R=R, n=n)
beta_mean = colSums(s$alpha * s$mu) /  s$X_column_scale_factors
beta2_l = s$alpha * s$mu2 / s$X_column_scale_factors**2
beta_l = s$alpha * s$mu / s$X_column_scale_factors
beta2_mean = colSums(beta2_l) + colSums(beta_l)**2 - colSums(beta_l * beta_l)
beta_var = beta2_mean - beta_mean**2
```

Thanks,

Omer

**Comment by gaow** [comment]
@omerwe what you did seems correct (`beta2_mean` also appears in equation B.37 of SuSiE paper), except for a minor issue in `beta_mean` scaling which edited directly on your post. I'll leave the ticket open for now, though, because this might be something we would like to add to our code. Thanks for raising the issue!

**Comment by stephens999** [comment]
maybe we should add
`susie_get_posterior_mean`
and 
`susie_get_posterior_sd`

?

Currently we have `coef` to extract coefficients, which includes
the intercept and behaves like glmnet (for example). And I guess this
will be the main/encouraged interface for most users. But it seems for power users
having posterior sd could well be useful, and then maybe it makes sense to have a matching
function for posterior mean (and presumably no need to include intercept in either).

**Comment by zouyuxin** [comment]
One easier way to compute the variance is
```
beta_var = colSums((s$alpha * s$mu2 - (s$alpha*s$mu)^2))/(s$X_column_scale_factors^2)
```
This comes from <a href="https://www.codecogs.com/eqnedit.php?latex=var(\mathbf{b})=var(\sum_{l=1}^{L}\mathbf{b}_l)=\sum_{l=1}^{L}var(\mathbf{b}_l)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?var(\mathbf{b})=var(\sum_{l=1}^{L}\mathbf{b}_l)=\sum_{l=1}^{L}var(\mathbf{b}_l)" title="var(\mathbf{b})=var(\sum_{l=1}^{L}\mathbf{b}_l)=\sum_{l=1}^{L}var(\mathbf{b}_l)" /></a> 
where <a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{b}_l" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbf{b}_l" title="\mathbf{b}_l" /></a> and <a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{b}_k" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbf{b}_k" title="\mathbf{b}_k" /></a> are independent.

<a href="https://www.codecogs.com/eqnedit.php?latex=var(\mathbf{b}_l)=E(\mathbf{b}_l^2)-E(\mathbf{b}_l)^2" target="_blank"><img src="https://latex.codecogs.com/gif.latex?var(\mathbf{b}_l)=E(\mathbf{b}_l^2)-E(\mathbf{b}_l)^2" title="var(\mathbf{b}_l)=E(\mathbf{b}_l^2)-E(\mathbf{b}_l)^2" /></a>

**Comment by zouyuxin** [comment]
Moreover, in the following simple example, the method @omerwe proposed gives negative variances, which may be caused by numerical errors.

example:
```
set.seed(1)
n = 100
p = 100
beta = rep(0,p)
beta[1:4] = 1
X = matrix(rnorm(n*p),nrow=n,ncol=p)
y = X %*% beta + rnorm(n)
s = susie(X,y,L=10)
```

**Comment by omerwe** [comment]
This is great, thanks!

**Comment by stephens999** [comment]
@zouyuxin can you implement `susie_get_posterior_mean` and `susie_get_posterior_sd` based
on these?

**Comment by zouyuxin** [comment]
sure, will do that.

**Comment by mkanai** [comment]
Hi, it seems there is a typo in `susie_get_posterior_mean`. Specifically,
https://github.com/stephenslab/susieR/blob/7f7da47da40b5f15a02795c27a023414f9995e2a/R/susie_utils.R#L453

This line should be: (replace s$mu with res$mu)
```{r}
colSums(res$alpha*res$mu)/res$X_column_scale_factors
```

Also, `susie_get_posterior_mean` and `susie_get_posterior_sd` are not currently exported. Do you have any plans to export them at some point?

Thanks!

**Comment by gaow** [comment]
@mkanai thank you for the feedback. We've fixed that typo and exported the functions. Please checkout the current `master` for version 0.8.1.0520.

**Comment by cindywen96** [comment]
This thread is very helpful! Thanks!
I had a question when using function `susie_get_posterior_mean `. When `include_idx` is a single number, I got an error
```
> colSums((susie_object$alpha * susie_object$mu)[1,])
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) :
  'x' must be an array of at least two dimensions
```
Any idea on this?
