### ISSUE TITLE
Eigen decomp step

### ISSUE THREAD

**Issue by julirsch** [stephenslab/susieR#86]
Hi SuSiE!

For the sum stats version of SuSiE (susie_z, susie_bhat), the eigen decomposition step in check_r_matrix (now set_R_attributes) take a long time for large matrices. I'm pretty sure this is just for the purpose of checking that the XtX matrix is positive semi-definite (at least in the version of SuSiE from January). It's easy to work around this and pre-process inputs for susie_ss, but perhaps susie_z and susie_bhat should have the option of not performing this eigen decomp?

Jacob

**Comment by gaow** [comment]
@julirsch we indeed have it planned [along the lines you suggested](https://github.com/stephenslab/susieR/issues/70#issuecomment-474558486), for this and for some other different checks. As you can see we are currently in the processes of re-vamping the summary statistics interface, hoping to clean up the interface soon. In the mean time you might have to manually comment out those lines for your purpose. 

As you can also see in the discussion I pointed above, there are caveats running summary statistics version of SuSiE. We will document and note it more formally in our updated interface too.

**Comment by julirsch** [comment]
@gaow great! I've done this manually for now. looking forward to hearing more about the caveats of ss SuSiE.
