### ISSUE TITLE
Add z score adjustment parameter to `susie_rss`

### ISSUE THREAD

**Issue by gaow** [stephenslab/susieR#98]
Separated from #91 

> (@stephens999 ) i suggest we should have a flag for susie_rss to add the z automatically? eg a z_ld_weight parameter,that specifies what weight should be assigned to the z in the ld matrix - it will use something like wzz' + (1-w) Rwhere R is the user specified LD matrix. The default could be 0.01 or 0....

@stephens999 I think we have talked about it at some point -- the approach was a bit heuristic and we were not sure what's the right `w` to use. So in a way we never finalized the issue. Are we now at the point where we can comfortably recommend what to do? If not, it may still help to add this parameter to the interface then we can assess it better. I only worry about a formal justification for it that warrants it to be considered a feature.

**Comment by zouyuxin** [comment]
Perhaps, we can add two parameters, z_ld_weight and n_ref, and user must specify one of them. If n_ref is given, the weight is 1/n_ref and this is what we used in simulation. Or we add this recommended weight in the documentation.

**Comment by stephens999** [comment]
I prefer one parameter.

We can recommend they use 1/nref

**Comment by zouyuxin** [comment]
I added `z_ld_weight` in susie_rss with this commit 33986e2
